config/routes.rb
Rails.application.routes.draw do
  root to: "pages#splash"

  get "/auth/github", as: :github_login
  get "/auth/github/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resource :users, only: [:show]
  get "/profile/following", to: "users#following", as: :following
  get "/profile/following/:username", to: "users#activity", as: :following_activity
  get "/profile/repos", to: "users#repos", as: :user_repo
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    user = where(username: auth_info.info.nickname).first_or_create do |new_user|
      new_user.username = auth_info.info.nickname
    end
    user.oauth_token        = auth_info.credentials.token
    user.oauth_token_secret = auth_info.credentials.secret
    user.save
    user
  end

  def info
    GithubService.new(self).user_info
  end

  def orgs
    GithubService.new(self).org_info
  end

  def repos
    GithubService.new(self).repo_info
  end

  # def commit_total
  #   event_hash = GithubService.new(self).event_info
  #   event_hash.map do |event|
  #     if event[:type] == "PushEvent" || event[:type] == "CreateEvent"
  #       event[:payload][:size]
  #     end
  #   end.compact.reduce(:+)
  # end

  def commits
    event_hash = GithubService.new(self).event_info
    event_hash.each_with_object(Hash.new(0)) do |event, hash|
      if event[:type] == "PushEvent" || event[:type] == "CreateEvent"
        hash[event[:repo][:name]] += 1
      end
    end
  end

  def followed_activity(username)
    event_hash = GithubService.new(self).followed_info(username)
    event_hash.each_with_object(Hash.new(0)) do |event, hash|
      if event[:type] == "PushEvent" || event[:type] == "CreateEvent"
        hash[event[:repo][:name]] += 1
      end
    end
  end

  def following
    list = GithubService.new(self).followed_list
    list.map do |info|
      {username: info[:login], avatar_url: info[:avatar_url]}
    end
  end
end

app/models/user_data.rb
class UserData < OpenStruct
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def splash
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:activity]

  def show
    @info = @user.info
    @orgs = @user.orgs
  end

  def following
  end

  def activity
    @info = current_user.followed_activity(params[:username])
  end

  def repos
  end

  private

    def set_user
      @user = current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="bar">
      <a class="brand-logo">API Curious</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user %>
          <li>Welcome, <%= current_user.username %></li>
        <% end %>
        <li>
          <% if current_user %>
            <%= link_to "Logout", logout_path, method: :delete %>
          <% else %>
            <%= link_to "Login", github_login_path %>
          <% end %>
        </li>
        <% if current_user %>
          <li>
            <%= link_to "Profile", users_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiCurious</title>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "layouts/navbar" %>
<% flash.each do |type, message| %>
  <%= content_tag :div, message.html_safe, class: "flash-#{type}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/splash.html.erb
<h1>Base Page</h1>

app/views/users/activity.html.erb
<div class="commits">
  <%= params[:username] %>'s Contribution Activity
  <% @info.each_pair do |key, value| %>
    <div>Pushed <%= value %> to <%= key %></div>
  <% end %>
</div>

app/views/users/following.html.erb
<h1>Followed Activity</h1>
<% @user.following.each do |followed| %>
  <div class="<%= followed[:username] %>">
    <a href="<%= following_activity_path(followed[:username]) %>">
      <img src="<%= followed[:avatar_url] %>" alt="<%= followed[:username] %>" />
    </a>
    <a href="<%= following_activity_path(followed[:username]) %>">
      <%= followed[:username] %>
    </a>
  </div>
<% end %>

app/views/users/repos.html.erb
<h1><%= @user.username %>'s Repositories</h1>
<% @user.repos.each do |repo| %>
  <div class="<%= repo[:name] %>">
    <%= link_to repo[:name], repo[:html_url] %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile">
  <img src="<%= @info[:avatar_url] %>" alt="Whatup" />
  <div class="basic-stats">
    <span id="followers">
      Followers: <%= @info[:followers] %>
    </span>
    <span id="starred">
      Starred: <%= @info[:starred] %>
    </span>
    <span id="following">
      <%= link_to "Following: #{@info[:following]}", following_path %>
    </span>
  </div>
</div>
<div class="commits">
  <h3>Contribution Activity</h3>
  <% @user.commits.each_pair do |key, value| %>
    <div>Pushed <%= value %> to <%= key %></div>
  <% end %>
</div>
<div id="orgs">
  <h3>Member of:</h3>
  <% if @orgs.empty? %>
    Not a single Organization
  <% else %>
    <% @orgs.each do |org| %>
      <div class="<%= org[:login] %>">
        <a href="<%= org[:url] %>"><img src="<%= org[:avatar_url] %>" alt="<%= org[:login] %>" /></a>
        <div><%= org[:login] %></div>
      </div>
    <% end %>
  <% end %>
</div>
<div id="repos">
  <%= link_to "Repositories", user_repo_path %>
</div>